- app/src/main/java/com/android/youtubeproject/API/ChannelData.kt
- app/src/main/java/com/android/youtubeproject/API/NetWorkInterface.kt
- app/src/main/java/com/android/youtubeproject/API/YoutubeModel.kt
- app/src/main/java/com/android/youtubeproject/Constants.kt
- app/src/main/java/com/android/youtubeproject/Fragment/HomeFragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/Fragment/HomeFragment/HomeFragmentAdapter.kt
- app/src/main/java/com/android/youtubeproject/ViewModel/HomeViewModel.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/recyclerview.xml
1. Home 어댑터 추가
2. API를 이용해서 데이터 받아옴(Constants에 각자 키입력해서 쓰세요)
3. ViewModel구현 시작
> [FEAT] : ⚙️ Home: API 데이터 받아오기(로그찍힘), ViewModel 구현중

- app/src/main/AndroidManifest.xml
- app/src/main/res/drawable/gradiant.xml
- app/src/main/res/drawable/tab_shape.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
[[DESIGN] : 🎨(featuremypage): 테마컬러 적용, 하단탭 shape지정
스타일파일 추가
그라디언트 파일추가
탭레이아웃 백그라운드 레이우스 적용
activoty_main 백그라운드에 적용
> Featuremypage

- app/build.gradle
- app/src/main/java/com/android/youtubeproject/Fragment/VideoDetailFragment/VideoDetail.kt
- app/src/main/res/drawable/video_detail_dialog_rounded_image.xml
- app/src/main/res/layout/activity_video_detail.xml
- app/src/main/res/layout/dialog_video_detail_information.xml
[FEAT] : ⚙️ 상세 페이지의 비디오 공유 기능 구현
> [FEAT] : ⚙️ 상세 페이지의 비디오 공유 기능 구현

- app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
- app/src/main/res/layout/dialog_video_detail_information.xml
[FEAT] : ⚙️ 홈 프래그먼트에서 비디오 상세 액티비티로 데이터 전달
class YoutubeModel 에 매개변수 추가,
class HomeFragment : Fragment()  에 86번째줄부터 91번째 줄 클릭 리스너 구현
class HomeViewMode 에 30번째줄부터 46번째 줄 추가한 데이터에 맞춰 항목을 추가하였습니다
> [FEAT] : ⚙️ 홈 프래그먼트에서 비디오 상세 액티비티로 데이터 전달

- app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
[FIX] : 🐛 함수 인자 위치 변경으로 인해 실행 안되던것 수정
> [FIX] : 🐛 함수 인자 위치 변경으로 인해 실행 안되던것 수정.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/android/youtubeproject/api/NetWorkClient.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/CustomDialog.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/DbDao.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/MyDatabase.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/MyEntity.kt
- app/src/main/res/drawable/ic_baseline_add_photo_alternate_24.xml
- app/src/main/res/drawable/text_button_bg.xml
- app/src/main/res/layout/dialog_layout.xml
- app/src/main/res/layout/fragment_my_video.xml
[FEAT] : 룸 적용 임시 비디오테이블, 유저테이블생성, 유저추가
> [FEAT] : 룸 적용 임시 비디오테이블, 유저테이블생성, 유저추가

- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyPageFunc.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragmentAdapter.kt
[[FEAT] : ⚙️(feature/myvideo): 상세페이지 데이터 저장 후, 마이페이지 연동
테스트를 위해서 임시로 아래 코드를 넣으면 바로 마이데이터에서 확인할 수 있습니다.
> [FEAT] : ⚙️(feature/myvideo): 상세페이지 데이터 저장 후, 마이페이지 연동

- .github/workflows/my_workflow.yml
> [FEAT] : ⚙️깃허브 풀리퀘 노션의 S.A와 연동(될지 안될지 모름)

- app/src/main/java/com/android/youtubeproject/api/HashMapData.kt
- app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
- app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
API 인터페이스 쿼리맵으로 일부 수정
쿼리값 오브젝트로 일부 옴김
> [FIX] : 🔧 NetWorkInterface : Query -> QueryMap 수정

- app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
- app/src/main/java/com/android/youtubeproject/api/model/NationModel.kt
- app/src/main/java/com/android/youtubeproject/api/serverdata/ChannelData.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModelFactory.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
1. ChannelViewModel 구현중 
2. 쿼리값에 넣어줄 채널id값들을 받아옴
> [FEAT] : ⚙️ ChannelViewModel 구현중 

- app/src/main/java/com/android/youtubeproject/api/model/ChannelModel.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeChannelAdapter.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModel.kt
1.  ChannelViewModel에 NationViewModel에서 id값들을 받아와서 쿼리값에 넣어줌
2. 서버에서 channel데이터를 받아와서 뷰모델+라이브데이터 적용
3. 해당 데이터를 앱에 표시
4. 이후 : Loading 라이브데이터 구현 목표
> [FEAT] : ⚙️ ChannelViewModel구현 앱에 데이터 표시

- app/src/main/java/com/android/youtubeproject/Constants.kt
- app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeChannelAdapter.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeNationAdapter.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
- app/src/main/res/layout/empty_view.xml
- app/src/main/res/layout/favoritesitems.xml
- app/src/main/res/layout/fragment_home.xml
1. Home화면에서 카테고리 선택했을때 서버에서 받은 데이터가 없을때 "결과가 없습니다" TextView출력
2. 데이터관련 예외처리
> [DESIGN] : 🎨 Home, [FIX] : 🐛 : 서버데이터가 없을때 "결과가 없습니다" TextView 표시, 예외 처리

- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
- app/src/main/res/layout/fragment_home.xml
1. Nation데이터, 채널 데이터 : 라이브데이터를 이용한 로딩 프로그레스 구현
2. 데이터 로딩중일때 프로그레스바 구현, 로딩이 끝나면 isLoading을 false로 바꿔서 숨긴다.
> [FEAT] : ⚙️ 카테고리 클릭 시 라이브데이터를 이용한 로딩프로그레스 구현

- app/src/main/res/layout/dialog_video_detail_information.xml
- app/src/main/res/layout/fragment_home.xml
성수님 영역인 홈 프래그먼트의 .xml에서 스크롤뷰와 constraintlayout를 추가하고, id도 작성하였습니다.
android:id="@+id/home_body_const_scroll"
android:id="@+id/home_body_const"
입니다.
> [DESIGN] : 🎨 홈프레그먼트 스크롤뷰 추가, 다이어로그 이미지 수정

- app/src/main/java/com/android/youtubeproject/MainActivity.kt
⚙️(feature/myvideo): 뷰페이저 슬라이드 차단
>  ⚙️(feature/myvideo): 뷰페이저 슬라이드 차단

- app/src/main/java/com/android/youtubeproject/FragmentActionListener.kt
- app/src/main/java/com/android/youtubeproject/MainActivity.kt
- app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyPageFunc.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragmentAdapter.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/DbDao.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/MyDatabase.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/MyEntity.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/repository/MyVideoRepository.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/viewmodel/MyVideoViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/layout_myvideo_item.xml
[REFACTOR] : ♻️(feature/myvideo): 마이비디오에 부분적으로 AAC적용
[FEAT] : ⚙️(feature/myvideo): 상세화면데이타 마이비디오 저장,삭제,존재여부 추가
[FEAT] : ⚙️(feature/myvideo): 홈 앱바에서 마이비디오 아이콘 누르면 마이페이지로 이동
[REFACTOR] : ♻️(feature/myvideo): 마이비디오 리스트아이템 데이터바인딩 적용
> 마이비디오 저장,삭제,존재여부 추가, 리스트에 데이터바인딩, AAC적용

- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
임시로 리줌에서 리스트아이템 갱신코드 추가함  - 개선예정
> [FIX] : 🔧(feature/myvideo): 좋아요 시, 마이비디오에 리스트갱신

- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragmentAdapter.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
비디오 상세에서 좋아요 버튼 연동
마이비디오에서 상세페이지 연동
> [FEAT] : ⚙️(feature/myvideo): 비디오 상세에서 좋아요 기능 추가, 마이비디오에서 상세 연결

- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/spf/SharedPref.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/values/colors.xml
1. 앱 재실행 시 마지막 카테고리목록 앱에 표시
2. 스피너 색상변경
> ⚙️ 🎨 Home: 카테고리 저장&로드/ 스피터 UI

- app/src/main/java/com/android/youtubeproject/Constants.kt
- app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
- app/src/main/java/com/android/youtubeproject/api/serverdata/ChannelData.kt
- app/src/main/java/com/android/youtubeproject/api/serverdata/SearchData.kt
- app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragmentAdapter.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/searchmodel/SearchViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/searchmodel/SearchViewModelFactory.kt
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/layout/searchitems.xml
1. SearchData 추가
2. 검색페이지 UI
3. 검색 후 데이터를 서버에서 받아오기 위한 API요청 함수 추가
4. 검색데이터 뷰모델+라이브 데이터 추가
5. 검색 페이지 앱에 표시 완료
> ⚙️🎨 검색페이지: 필수기능 구현&UI

- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModel.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModelFactory.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoRepository.kt
- app/src/main/res/layout/activity_video_detail.xml
[DESIGN][FIX] : 🎨🔧 앱바 추가&버튼 위치 수정, MVVM패턴 적용중
> [DESIGN][FIX] : 🎨🔧 앱바 추가&버튼 위치 수정, MVVM패턴 적용중

- app/src/main/java/com/android/youtubeproject/MainActivity.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/CustomDialog.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyPageFunc.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/DbDao.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/MyEntity.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/repository/MyVideoRepository.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/viewmodel/MyVideoViewModel.kt
- app/src/main/res/values/strings.xml
[FIX] : 🔧(feature/myvideo): 다이얼로그에 기존 저장한 프로필 정보 표시하도록 적용
[FEAT] : ⚙️(feature/myvideo): 마이비디오 갱신 시, 홈과 마이비디오 영역에 동기화 (검색화면은 추후)
[FIX] : 🔧(feature/myvideo): 도큐먼트에서 획득한 이미지에 대해 영구적 권한 추가 / 유저 정보 저장 완료 후 갱신 기능 추가
> 프로필 갱신 시, 홈과 마이비디오 영역, 다이얼로그 동기화  (검색화면은 추후)

- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModel.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoRepository.kt
> [FIX] : 🔧 MVVM패턴 적용중

- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/infinityscroll/FavoritesScrollListener.kt
- app/src/main/java/com/android/youtubeproject/infinityscroll/NationScrollListener.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
- app/src/main/res/layout/fragment_home.xml
- build.gradle
1. 스크롤 관련 클래스 생성( HomeViewModel& NationViewModel 두 곳에서 받는 파라미터가 달라서 클래스2개 생성)
2. Home에서 infinity Scroll구현 완료( 항목 50개까지)
> [FEAT] : ⚙️ Home : infinity Scroll 구현

- app/src/main/java/com/android/youtubeproject/api/model/NationModel.kt
- app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeNationAdapter.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
1. 변수명을 보기 쉽게 변경중
2. NationModel을 없애고 YoutubeModel로 통합
> [DOCS] : 📚 Home : 변수명 변경

- app/src/main/java/com/android/youtubeproject/api/model/CategoryModel.kt
- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
- app/src/main/java/com/android/youtubeproject/infinityscroll/SearchScrollListener.kt
- app/src/main/java/com/android/youtubeproject/method/method.kt
- app/src/main/java/com/android/youtubeproject/spf/SPF.kt
- app/src/main/java/com/android/youtubeproject/spf/SharedPref.kt
- app/src/main/res/drawable/outline.xml
- app/src/main/res/layout/favoritesitems.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_search.xml
1. 검색페이지에서 카테고리 선택할 수있는 스니펫 추가
2. 카테고리를 선택하면 검색어를 입력하라는 토스트 메시지 추가
3. 카테고리를 선택하지않고 검색을 하면 카테고리를 선택하라는 토스트 메시지 추가
> [FEAT] : ⚙️ 검색페이지 : 카테고리 선택 추가

- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/CustomDialog.kt
- app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyPageFunc.kt
- app/src/main/res/layout/dialog_layout.xml
[FEAT] : ⚙️(feature/myvideo): 프로필 이미지 삭제 추가
> [FEAT] : ⚙️(feature/myvideo): 프로필 이미지 삭제 추가

- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
- app/src/main/java/com/android/youtubeproject/infinityscroll/NationScrollListener.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/searchmodel/SearchViewModel.kt
- app/src/main/res/layout/favoritesitems.xml
1. Home에서 카테고리선택 후 인피니티 스크롤 시 다른카테고리 목록이 나오는 에러 해결
2. Search에서 검색 했을때 api호출이 중복되는 오류 해결
3. 항목아이템 title maxLine 2줄로 수정
> [FIX] : 🐛 Home&Search 에러수정

- app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
- app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
- app/src/main/java/com/android/youtubeproject/infinityscroll/FavoritesScrollListener.kt
- app/src/main/java/com/android/youtubeproject/infinityscroll/NationScrollListener.kt
- app/src/main/java/com/android/youtubeproject/infinityscroll/SearchScrollListener.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
- app/src/main/java/com/android/youtubeproject/viewmodel/searchmodel/SearchViewModel.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_search.xml
1. Home, Search 항목 갯수표시
2. UI, 디자인 일부 변경
> [DESIGN] : 🎨 UI변경 : 항목 갯수 표시, UI변경

- app/src/main/java/com/android/youtubeproject/SplashActivity.kt
- app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
- app/src/main/res/layout/activity_splash.xml
> [FIX] : 🔧 스플래쉬 화면 조금 수정

- app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragmentAdapter.kt
검색결과가 없을때 "검색 결과가 없습니다." TextView를 화면에 표시한다.
> [FEAT] : ⚙️ 검색결과예외 처리
